[package]
name = "zipstream"
version = "1.0.1"
authors = ["Kevin Mehall <kevin.mehall@3drobotics.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
futures = "0.3.4"
futures-util = "0.3.4"
bytes = "0.5.4"
regex = "1.0.5"
tokio = { version = "0.2.11", features = ["stream"] }
hyper = "0.13.6"
hyper-tls = "0.4.1"
rusoto_s3 = "0.44.0"
rusoto_core = "0.44.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
log = "0.4.6"
log-panics = "2.0.0"
env_logger = "0.6.0"
clap = "2"
lazy_static = "1.1.0"
chrono = { version = "0.4", features = ["serde"] }
jemallocator = "0.3.0"
jemalloc-sys = { version = "0.3.0", features = ["background_threads"] }
